name: chat
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0         # For date/time formatting
  provider: ^6.1.2        # For simple state management (themes, settings)
  shared_preferences: ^2.2.3 # For saving settings locally
  flutter_analog_clock: ^1.0.3 # A pre-built analog clock widget (easier than full CustomPainter initially)
  # Potentially needed later for other features:
  # flutter_local_notifications: ^17.1.2 # For Alarms/Timer notifications
  # workmanager: ^0.5.2              # For reliable background tasks (Alarms)
  # sqflite: ^2.3.3+1                 # For storing complex data like Alarms list
  # path_provider: ^2.1.3            # To find correct db storage path for sqflite
  # timezone: ^0.9.3                 # For World Clock timezone data
  # flutter_native_timezone: ^2.0.0   # To get the device's local timezone
  # audioplayers: ^6.0.0             # For alarm sounds / ticking
  # wakelock_plus: ^1.2.0           # To keep screen awake

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
